#!/usr/bin/env bash
# Generate one k8s Deployment per model from deploy/k8s/models.txt.
#
# Each pod serves exactly one model (the simulator binary is single-model by design).
# The orchestrator discovers all of them via the foundry.workload=vllm label and
# learns the model name by calling /v1/models on each pod.
#
# Usage:
#   ./scripts/generate-manifests.sh
#   kubectl apply -f deploy/k8s/generated/all-models.yaml
#
# Override the input file or output dir:
#   MODELS_FILE=my-models.txt OUTPUT_DIR=out ./scripts/generate-manifests.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MODELS_FILE="${MODELS_FILE:-$REPO_ROOT/deploy/k8s/models.txt}"
OUTPUT_DIR="${OUTPUT_DIR:-$REPO_ROOT/deploy/k8s/generated}"
OUTPUT_FILE="$OUTPUT_DIR/all-models.yaml"

NAMESPACE="${NAMESPACE:-foundry-simulator}"
IMAGE="${IMAGE:-ini8labs/image-model-simulator:latest}"
IMAGE_PULL_POLICY="${IMAGE_PULL_POLICY:-Always}"

# Defaults applied when a row omits a field.
DEFAULT_REPLICAS=3
DEFAULT_MIN_LATENCY=4000
DEFAULT_MAX_LATENCY=8000
DEFAULT_STARTUP_DELAY=10

if [[ ! -f "$MODELS_FILE" ]]; then
  echo "error: models file not found: $MODELS_FILE" >&2
  exit 1
fi

mkdir -p "$OUTPUT_DIR"

# Slugify a model name into a DNS-1123-safe k8s name fragment:
#   - lowercase
#   - replace any non-[a-z0-9] with '-'
#   - collapse repeated '-'
#   - trim leading/trailing '-'
#   - truncate to 59 chars (leaves room for the "sim-" prefix within k8s's 63-char limit)
slugify() {
  local name="$1"
  local slug
  slug=$(printf '%s' "$name" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's/[^a-z0-9]+/-/g; s/^-+//; s/-+$//')
  printf '%s' "${slug:0:59}"
}

# Reset output file.
{
  echo "# Auto-generated by scripts/generate-manifests.sh"
  echo "# Source: $(basename "$MODELS_FILE")"
  echo "# Do not edit by hand — re-run the generator after editing the source."
} > "$OUTPUT_FILE"

count=0
total_pods=0
seen_slugs=" "

while IFS= read -r raw_line || [[ -n "$raw_line" ]]; do
  # Strip comments and trim whitespace.
  line="${raw_line%%#*}"
  line="$(printf '%s' "$line" | awk '{$1=$1; print}')"
  [[ -z "$line" ]] && continue

  # Parse fields.
  # shellcheck disable=SC2206
  fields=($line)
  model_name="${fields[0]}"
  replicas="${fields[1]:-$DEFAULT_REPLICAS}"
  min_latency="${fields[2]:-$DEFAULT_MIN_LATENCY}"
  max_latency="${fields[3]:-$DEFAULT_MAX_LATENCY}"
  startup_delay="${fields[4]:-$DEFAULT_STARTUP_DELAY}"

  slug="$(slugify "$model_name")"
  if [[ -z "$slug" ]]; then
    echo "error: model name '$model_name' slugifies to empty string" >&2
    exit 1
  fi

  deployment_name="sim-$slug"

  if [[ "$seen_slugs" == *" $deployment_name "* ]]; then
    echo "error: duplicate deployment name '$deployment_name' from model '$model_name' (two source rows slugify to the same name)" >&2
    exit 1
  fi
  seen_slugs="$seen_slugs$deployment_name "

  cat >> "$OUTPUT_FILE" <<EOF

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $deployment_name
  namespace: $NAMESPACE
  labels:
    app: $deployment_name
    foundry.simulator: "true"
    foundry.model: "$model_name"
spec:
  replicas: $replicas
  selector:
    matchLabels:
      app: $deployment_name
  template:
    metadata:
      labels:
        app: $deployment_name
        foundry.workload: vllm
        foundry.simulator: "true"
        foundry.model: "$model_name"
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: simulator
          image: $IMAGE
          imagePullPolicy: $IMAGE_PULL_POLICY
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: admin
              containerPort: 9000
              protocol: TCP
          env:
            - name: MODEL_NAME
              value: "$model_name"
            - name: PORT
              value: "8000"
            - name: ADMIN_PORT
              value: "9000"
            - name: MIN_LATENCY_MS
              value: "$min_latency"
            - name: MAX_LATENCY_MS
              value: "$max_latency"
            - name: STARTUP_DELAY_S
              value: "$startup_delay"
            - name: LOG_LEVEL
              value: "info"
          startupProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 5
            failureThreshold: 60
          readinessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: http
            periodSeconds: 20
            failureThreshold: 6
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
EOF

  count=$((count + 1))
  total_pods=$((total_pods + replicas))
  printf '  generated %-40s -> %s (%d replicas)\n' "$model_name" "$deployment_name" "$replicas"
done < "$MODELS_FILE"

if [[ $count -eq 0 ]]; then
  echo "error: no models found in $MODELS_FILE" >&2
  exit 1
fi

echo
echo "wrote $count Deployments ($total_pods pods total) to $OUTPUT_FILE"
echo
echo "next steps:"
echo "  kubectl apply -f $OUTPUT_FILE"
echo "  kubectl get deploy -n $NAMESPACE -l foundry.simulator=true"
